### ISSUE TITLE
Replace deprecated dependency react-addons-css-transition-group

### ISSUE THREAD

**Issue by punya** [palantir/blueprint#1051]
### Bug report

- __Package version(s)__: 1.16.0
- __Browser and OS versions__: Chrome 57 on OSX (but it doesn't matter)

#### Steps to reproduce

1. Install Blueprint using YARN

#### Actual behavior

Requires the deprecated `react-addons-css-transition-group` package as a peer dependency.

#### Expected behavior

Allows (preferably, recommends) the [react-transition-group](https://github.com/reactjs/react-transition-group) fork, as recommended by the README for [react-addons-css-transition-group](https://www.npmjs.com/package/react-addons-css-transition-group).

**Comment by benhjames** [comment]
Are you accepting PRs for this? Would quite happily fix!

**Comment by llorca** [comment]
@benhjames for sure, we'd appreciate a contrib!

**Comment by remziduzagac** [comment]
Im still having this error with 1.17.1 version. is that normal?

**Comment by benhjames** [comment]
Yeah - it's a breaking change so it was decided to release with 2.0.0 instead - the patch 1.17.1 reverted the fix. 🙂

**Comment by remziduzagac** [comment]
☺ thank you very much

23 May 2017 18:55 tarihinde "Ben James" <notifications@github.com> yazdı:

**Comment by tangert** [comment]
is this still open? dealing with this error right now, trying to figure it out. has an update been made that fixes the break?

**Comment by rohmanhm** [comment]
Anybody would like make a PR I'll appreciated.

**Comment by benhjames** [comment]
The PR that fixed this was reverted since it is a breaking change, and will likely release with v2.0.0 of Blueprint. :)

**Comment by mkmpvtltd1** [comment]
i have same issue how can i fix this?

**Comment by giladgray** [comment]
@mkmpvtltd1 ignore it! It's not an error, just a casual warning. Your app will continue to function perfectly despite the outdated library. 

We'll bump all our dependencies later this year.

**Comment by jsina** [comment]
I've get the same error
"Uncaught Error: Cannot find module "react-addons-css-transition-group"
 
here is my package.json
```
"dependencies": {
    "@blueprintjs/core": "^1.27.0",
...
```

**Comment by ChisholmKyle** [comment]
I'm trying to upgrade to React 16. If I try to build without the `react-addons-css-transition-group` dependency, I get this error when running browserify:

    Error: Cannot find module 'react-addons-css-transition-group' from '/path/to/project/node_modules/@blueprintjs/core/dist/components/overlay'

So I try to install "`react-addons-css-transition-group`" but the module does not support React 16. However if I try to install an alpha version compatible with React 16 as follows: 

    npm install --save-dev react-addons-css-transition-group@^16.0.0-alpha

I get an error that it's incompatible with Blueprintjs:

    npm ERR! peerinvalid The package react-addons-css-transition-group@16.0.0-alpha.3 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer @blueprintjs/core@1.31.0 wants react-addons-css-transition-group@^15.0.1 || ^0.14

Is it possible to use blueprintjs v1.x with React 16? I thought there was an update recently to at least try it out.

**Comment by giladgray** [comment]
@ChisholmKyle in my testing, it seemed that `react-addons-css-transition-group@15` totally supports React 16! I wasn't even aware there was an alpha, or that such a thing would be necessary (pretty sure it isn't).

it's unsupported by the React dev team (hence the new package), but the existing API is still fully functional. so you should be able to install it alongside Blueprint using a version that matches our `peerDependency`.

either way, this'll be like the first thing we do when we begin work on 2.0 later this year.

**Comment by giladgray** [comment]
@jsina you must declare your own dependencies on react, react-dom, and react-addons-css-transition-group because we declare them as `peerDependencies.` https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by ChisholmKyle** [comment]
I found out my problem. I'm using typescript and it was actually the package `@types/pure-render-decorator` causing the problem. When I removed that dependency from package.json, React 16 is now working with blueprint.js and `react-addons-css-transition-group`!

Thanks for your help.
