### ISSUE TITLE
After updated to 1.2.0 DateInput doesn't work

### ISSUE THREAD

**Issue by alearcy** [palantir/blueprint#322]
### Bug report

- __Package version(s)__:  1.2.0
- __Browser and OS versions__: Chrome 54.0.2840.98 (64-bit), Max OS Sierra

#### Steps to reproduce

with ReduxForm I have a pure function component with DateInput:
```ts
const nextYears = new Date(2040, 12, 31);
const renderDate = ({ input, label, type, meta: { touched, error } }) => (
	<div className="input-margin-bottom date-fill">
		<label className="pt-label">{label}</label>
		<DateInput {...input} locale="it" format="DD-MM-YYYY" maxDate={nextYears} position={Position.BOTTOM_RIGHT} className="pt-fill" />
		<div className='text-danger'>{touched ? error : ''}</div>
	</div>
);
```
#### Actual behavior

`Uncaught TypeError: date.getFullYear is not a function`

that refers to:

```ts
this.fromDateToMoment = function (date) {
            return moment([
                date.getFullYear(),
                date.getMonth(),
                date.getDate(),
                date.getHours(),
                date.getMinutes(),
                date.getSeconds(),
                date.getMilliseconds(),
            ]);
        };
```

**Comment by mfedderly** [comment]
This appears to happen if the value prop is explicitly assigned to `null` (and not `undefined`).

**Comment by giladgray** [comment]
We typically treat those two values as identical, using `== null` for comparison.

**Comment by alearcy** [comment]
Should I write something like this?

`<DateInput value={input.value || undefined} locale="it" format="DD-MM-YYYY" maxDate={nextYears} position={Position.BOTTOM_RIGHT} className="pt-fill" />`

**Comment by mfedderly** [comment]
@alearcy I suspect that will unblock you in the short term, until the fix from #323 is published.

**Comment by alearcy** [comment]
Thank you so much guys..it's an important work for my customer ;-)

**Comment by alearcy** [comment]
Guys, it is possible to release a 1.2.1 version instead of waiting 1.3 for this small fix?
