### PR TITLE
📦 Switch to Yarn workspaces; overhaul build system

### LINKED ISSUE #116: Speed up CI builds with parallelization
As a first stab, we should investigate if we can run the different packages' unit tests in different containers.

### LINKED ISSUE #436: Optimize webpack builds in distribution and preview scripts
There are a few simple things that could be improved in the webpack bundling setup:

- [x] use any/all relevant [webpack optimization options](https://github.com/webpack/docs/wiki/optimization) in the gulp code that generates configs for creating the package distributions ([webpack-config.js](https://github.com/palantir/blueprint/blob/f02ee9d22e2db651f020e7fa7d43439443bb7c1d/gulp/util/webpack-config.js))
- [x] ensure that all preview pages use production react & the same optimization options to simulate a realistic test environment. currently, packages/table doesn't do this; it has a [pretty basic webpack setup](https://github.com/palantir/blueprint/blob/f02ee9d22e2db651f020e7fa7d43439443bb7c1d/packages/table/config/webpack.config.preview.js).

### LINKED ISSUE #780: Test compilation errors do not fail karma tasks
Discovered in https://github.com/palantir/blueprint/pull/775#issuecomment-284160519

Current compilation failures are fixed in https://github.com/palantir/blueprint/pull/779, but we need to fix the build system to fail on `tsc` errors. I tried to get this working using solutions from https://github.com/TypeStrong/ts-loader/issues/108 but did not succeed. A quick and dirty fix would be to run `tsc -p packages/<name>/test` commands in the verify script or in `gulp check`. Or we could try upgrading to webpack 2 (shouldn't be too hard; I just did it on another project).

### LINKED ISSUE #1031: update @types in development
been a long time since we updated our `@types` dependencies. wonder what new hotness we're missing?? i know React types have come a long way...

### LINKED ISSUE #1527: [Labs/Select] Errors in popper.js typings
### Bug report

- __Package version(s)__:  typescript: 2.5.2, blueprintjs/labs: 0.8.0

#### Steps to reproduce

https://gist.github.com/slavasitnikov/887e240be9b08b35d0b67516d4e6ce08

```
npm i
./node_modules/.bin/tsc
```

#### Actual behavior
Compilation errors:

```
node_modules/popper.js/index.d.ts(38,5): error TS2411: Property 'shift' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(39,5): error TS2411: Property 'offset' of type '(BaseModifier & { offset?: string | number | undefined; }) | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(42,5): error TS2411: Property 'preventOverflow' of type '(BaseModifier & { priority?: Position[] | undefined; padding?: number | undefined; boundariesElem...' is not assignable to string index type 'Base
Modifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(47,5): error TS2411: Property 'keepTogether' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(48,5): error TS2411: Property 'arrow' of type '(BaseModifier & { element?: string | Element | undefined; }) | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(51,5): error TS2411: Property 'flip' of type '(BaseModifier & { behavior?: Position[] | "flip" | "clockwise" | "counterclockwise" | undefined; ...' is not assignable to string index type 'BaseModifier &
Record<string, any>'.
node_modules/popper.js/index.d.ts(56,5): error TS2411: Property 'inner' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(57,5): error TS2411: Property 'hide' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(58,5): error TS2411: Property 'applyStyle' of type '(BaseModifier & { onLoad?: Function | undefined; gpuAcceleration?: boolean | undefined; }) | unde...' is not assignable to string index type 'BaseModif
ier & Record<string, any>'.
```

It seems it is the same bug here: https://github.com/FezVrasta/popper.js/issues/414

### PR DESCRIPTION
**Pull request by adidahiya**
Fixes #1031.
Fixes #116.
Fixes #436.
Fixes #1527.
Fixes #780.

See https://github.com/palantir/blueprint/pull/1786 for more details about the build system overhaul.

#### Changes proposed in this pull request:

- Upgrade dev setup to Node 8.5 and Yarn 1.0
  - I did not upgrade `engines` in `package.json` because this all probably still works in Node 6... (no it's not worth testing for it in CI, if we get bug report we can just bump `engines` to the range we care about)
- Switch to using [Yarn workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/)
  - This makes installs faster, forces us to be more consistent about sharing the same dependencies across packages, and makes lockfile resolution easier.
- Bump various dev dependencies within existing semver ranges
- Bump documentalist
- Bump chai
- Bump stylelint-scss
- Bump ts-loader
- Bump webpack from v1 to v3!!

### CODE REVIEW

**Comment by adidahiya** [comment]
I think our version of webpack doesn't like resolving `node_modules` at the root... or we might have to explicitly add `../../node_modules` as to the list of bundler resolution paths.

File: package.json [hunk 1]
```diff
@@ -46,60 +49,60 @@
...
+    "ts-loader": "^3.0.3",
+    "ts-quick-docs": "^0.5.3",
     "tslint": "^5.7.0",
-    "tslint-config-prettier": "^1.5.0",
-    "tslint-plugin-prettier": "^1.1.0",
+    "tslint-config-prettier": "^1.6.0",
+    "tslint-plugin-prettier": "^1.3.0",
     "tslint-react": "^3.2.0",
-    "typescript": "~2.2.1",
+    "typescript": "~2.4.2",
```
Comment (giladgray) [inline package.json]: 😱 hooray! is this a safe change for .d.ts compatibility?

File: packages/core/src/common/abstractComponent.ts [hunk 2]
```diff
@@ -42,9 +42,9 @@ export abstract class AbstractComponent<P, S> extends React.Component<P, S> {
      * @returns a "cancel" function that will clear timeout when invoked.
      */
     public setTimeout(callback: () => void, timeout?: number) {
-        const handle = setTimeout(callback, timeout);
+        const handle = window.setTimeout(callback, timeout);
         this.timeoutIds.push(handle);
-        return () => clearTimeout(handle);
+        return () => window.clearTimeout(handle);
```
Comment (giladgray) [inline packages/core/src/common/abstractComponent.ts]: curious: why add the `window` reference?

File: packages/core/test/callout/calloutTests.tsx [hunk 3]
```diff
@@ -29,13 +29,6 @@ describe("<Callout>", () => {
         assert.isTrue(wrapper.hasClass(Classes.INTENT_DANGER));
     });
 
-    it("spreads HTML props", () => {
```
Comment (giladgray) [inline packages/core/test/callout/calloutTests.tsx]: why remove this test?

File: packages/docs/src/tags/heading.tsx [hunk 4]
```diff
@@ -14,7 +14,7 @@ const Heading: React.SFC<IHeadingTag> = ({ level, route, value }) =>
     React.createElement(
         `h${level}`,
         { className: "docs-title" },
-        <a className="docs-anchor" key="anchor" name={route} />,
```
Comment (giladgray) [inline packages/docs/src/tags/heading.tsx]: wait I think this attribute is critical to functionality! there's a selector that checks the `name` attr (although something is currently broken #1682)

File: packages/site-docs/package.json [hunk 5]
```diff
@@ -1,5 +1,5 @@
 {
-  "name": "blueprintjs.com/docs",
+  "name": "@blueprintjs/site-docs",
```
Comment (giladgray) [inline packages/site-docs/package.json]: idea behind the previous name was that it's obvious that the package is not published. I'm sure you ran into the issue where `/` is an invalid char in yarn package names. how about `blueprintjs.com-docs`?

File: packages/site-landing/src/require-shim.d.ts [hunk 6]
```diff
@@ -1,14 +0,0 @@
-/**
- * Copyright 2016 Palantir Technologies, Inc. All rights reserved.
- * Licensed under the BSD-3 License as modified (the “License”); you may obtain a copy
- * of the license at https://github.com/palantir/blueprint/blob/master/LICENSE
- * and https://github.com/palantir/blueprint/blob/master/PATENTS
- */
-
-// borrowed from https://github.com/TypeStrong/ts-loader
-
-declare var require: {
```
Comment (giladgray) [inline packages/site-landing/src/require-shim.d.ts]: awesome that we can delete this! where does the type info come from now?

File: package.json [hunk 7]
```diff
@@ -16,23 +19,23 @@
...
+    "@types/chai": "^4.0.4",
+    "@types/classnames": "^2.2.3",
+    "@types/dom4": "^1.5.20",
+    "@types/enzyme": "^2.8.0",
+    "@types/mocha": "^2.2.43",
+    "@types/pure-render-decorator": "^0.2.28",
+    "@types/react": "^16.0.14",
+    "@types/react-addons-css-transition-group": "^15.0.3",
+    "@types/react-addons-transition-group": "^15.0.1",
+    "@types/react-dom": "^16.0.1",
```
Comment (giladgray) [inline package.json]: 🎆 awesome sauce! although might it be more accurate to use the latest 15.x types instead?

File: packages/core/src/common/abstractComponent.ts (hunk 2 above)
Comment (adidahiya) [reply packages/core/src/common/abstractComponent.ts]: with dependency hoisting, we get `@types/node` at the root. the global `setTimeout` resolves to node's `setTimeout` before it sees `window.setTimeout` in lib.d.ts. so we make this more explicit

File: packages/core/test/callout/calloutTests.tsx (hunk 3 above)
Comment (adidahiya) [reply packages/core/test/callout/calloutTests.tsx]: I didn't find it very useful, and it was using invalid HTML props

File: packages/site-docs/package.json (hunk 5 above)
Comment (adidahiya) [reply packages/site-docs/package.json]: I find it weird that this monorepo doesn't follow the standard of using a single NPM scope. `"private": true` should make that publishing fact obvious enough.

File: packages/site-landing/src/require-shim.d.ts (hunk 6 above)
Comment (adidahiya) [reply packages/site-landing/src/require-shim.d.ts]: `@types/node` at the root

File: packages/docs/src/tags/heading.tsx (hunk 4 above)
Comment (adidahiya) [reply packages/docs/src/tags/heading.tsx]: `name` is not a valid HTML anchor attribute according to the latest `lib.d.ts`

File: package.json (hunk 7 above)
Comment (adidahiya) [reply package.json]: The types are basically the same and it's much easier to upgrade everything to latest; we won't be able to use new features at runtime anyway since we run react 15 in development.

File: package.json (hunk 1 above)
Comment (adidahiya) [reply package.json]: Should be safe since we're not using new features, but there are no guarantees. I would just highlight the small chance of breaking syntax in the release notes and file it as a low priority issue to fix in the future. I don't want to wait until the next major version to upgrade typescript.

File: packages/docs/src/tags/heading.tsx (hunk 4 above)
Comment (giladgray) [reply packages/docs/src/tags/heading.tsx]: `data-name` then please

File: packages/core/src/common/abstractComponent.ts (hunk 2 above)
Comment (giladgray) [reply packages/core/src/common/abstractComponent.ts]: would be cool to add a code comment to that effect

File: package.json (hunk 7 above)
Comment (giladgray) [reply package.json]: definitely buy the upgrade/similarity arguments, but my concern with this change is that new features are available at compile time but not at run time.

if you're not concerned then I'm chill.

File: packages/core/src/common/abstractComponent.ts (hunk 2 above)
Comment (adidahiya) [reply packages/core/src/common/abstractComponent.ts]: it's pretty obvious when you make the mistake. it's a compile error. the typedef takes you to a different file. not going to add a comment

Comment (giladgray) [reply packages/core/src/common/abstractComponent.ts]: what do you think about tslint `ban`ning non-window references to `set/clearTimeout/Interval`?

**Comment by giladgray** [comment]
@adidahiya I think the build stuff is now in a good state here! Tasks are working and development is possible. Now, all that remains should be some test fixes to get a passing build!

@cmslewis would you mind contributing fixes for the table tests?

**Comment by adidahiya** [comment]
recent changes lgtm

**Comment by adidahiya** [comment]
ready to go
