### PR TITLE
Fix DateInput throws error on null dates.

### LINKED ISSUE #322: After updated to 1.2.0 DateInput doesn't work
### Bug report

- __Package version(s)__:  1.2.0
- __Browser and OS versions__: Chrome 54.0.2840.98 (64-bit), Max OS Sierra

#### Steps to reproduce

with ReduxForm I have a pure function component with DateInput:
```ts
const nextYears = new Date(2040, 12, 31);
const renderDate = ({ input, label, type, meta: { touched, error } }) => (
	<div className="input-margin-bottom date-fill">
		<label className="pt-label">{label}</label>
		<DateInput {...input} locale="it" format="DD-MM-YYYY" maxDate={nextYears} position={Position.BOTTOM_RIGHT} className="pt-fill" />
		<div className='text-danger'>{touched ? error : ''}</div>
	</div>
);
```
#### Actual behavior

`Uncaught TypeError: date.getFullYear is not a function`

that refers to:

```ts
this.fromDateToMoment = function (date) {
            return moment([
                date.getFullYear(),
                date.getMonth(),
                date.getDate(),
                date.getHours(),
                date.getMinutes(),
                date.getSeconds(),
                date.getMilliseconds(),
            ]);
        };
```

### PR DESCRIPTION
**Pull request by mfedderly**
#### Changes proposed in this pull request:

- Properly check for null/undefined dates

### CODE REVIEW

File: packages/datetime/src/dateInput.tsx [hunk 1]
```diff
@@ -343,6 +343,10 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
      * This is a no-op unless moment-timezone's setDefault has been called.
      */
     private fromDateToMoment = (date: Date) => {
+        if (null == date) {
```
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: do we need a corresponding check in `fromMomentToDate`?

Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: please reverse, for consistency. `date == null`, that's just how we do it.

Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: check the constructor, where this function is called. i think `defaultValue` and `value` should both check `!= null` instead of whatever they're doing now. that might fix the `null` vs `undefined` distinction

Comment (mfedderly) [inline packages/datetime/src/dateInput.tsx]: I don't think we do, but I'll just add one to be safe.

Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: oh wait nvm it's not that simple. see the docs for the props. `null` and `undefined` actually mean different things here.

> To display no date in the input field, pass `null` to the value prop.

File: packages/datetime/src/dateInput.tsx [hunk 2]
```diff
@@ -327,6 +327,10 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
      * This is a no-op unless moment-timezone's setDefault has been called.
      */
     private fromMomentToDate = (momentDate: moment.Moment) => {
+        if (momentDate == null) {
+            return null;
```
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: probably want to return `undefined` actually. @adidahiya?

Comment (adidahiya) [inline packages/datetime/src/dateInput.tsx]: yeah, I would never explicitly return `null` in our code (but this is an outdated diff)

**Comment by adidahiya** [comment]
Github is being silly; the latest commit is green but the PR still shows "waiting for status to be reported". merging
