### ISSUE TITLE
Typescript 4.8 support

### ISSUE THREAD

**Issue by pxnis** [palantir/blueprint#5732]
compareUtils.filterKeys is incompatible with typescript 4.8

Tested with
- @blueprintjs/core: 4.12.0
- Typescript 4.8.4 (no problems with 4.7.4)

Log output:
```
node_modules/@blueprintjs/core/src/common/utils/compareUtils.ts(162,35): error TS2769: No overload matches this call.
  Overload 1 of 2, '(o: {}): string[]', gave the following error.
    Argument of type 'T' is not assignable to parameter of type '{}'.
  Overload 2 of 2, '(o: object): string[]', gave the following error.
    Argument of type 'T' is not assignable to parameter of type 'object'.
```

**Comment by adidahiya** [comment]
I think this is fixed now that we've updated to TypeScript 4.8 in this repo.

I've also verified the latest version of @blueprintjs/core works with TypeScript 4.8 in this new code sandbox: https://codesandbox.io/p/sandbox/blueprint-sandbox-2023-fjo3z4
