### PR TITLE
Refactor build system, remove Gulp

### LINKED ISSUE #116: Speed up CI builds with parallelization
As a first stab, we should investigate if we can run the different packages' unit tests in different containers.

### LINKED ISSUE #436: Optimize webpack builds in distribution and preview scripts
There are a few simple things that could be improved in the webpack bundling setup:

- [x] use any/all relevant [webpack optimization options](https://github.com/webpack/docs/wiki/optimization) in the gulp code that generates configs for creating the package distributions ([webpack-config.js](https://github.com/palantir/blueprint/blob/f02ee9d22e2db651f020e7fa7d43439443bb7c1d/gulp/util/webpack-config.js))
- [x] ensure that all preview pages use production react & the same optimization options to simulate a realistic test environment. currently, packages/table doesn't do this; it has a [pretty basic webpack setup](https://github.com/palantir/blueprint/blob/f02ee9d22e2db651f020e7fa7d43439443bb7c1d/packages/table/config/webpack.config.preview.js).

### LINKED ISSUE #780: Test compilation errors do not fail karma tasks
Discovered in https://github.com/palantir/blueprint/pull/775#issuecomment-284160519

Current compilation failures are fixed in https://github.com/palantir/blueprint/pull/779, but we need to fix the build system to fail on `tsc` errors. I tried to get this working using solutions from https://github.com/TypeStrong/ts-loader/issues/108 but did not succeed. A quick and dirty fix would be to run `tsc -p packages/<name>/test` commands in the verify script or in `gulp check`. Or we could try upgrading to webpack 2 (shouldn't be too hard; I just did it on another project).

### LINKED ISSUE #1527: [Labs/Select] Errors in popper.js typings
### Bug report

- __Package version(s)__:  typescript: 2.5.2, blueprintjs/labs: 0.8.0

#### Steps to reproduce

https://gist.github.com/slavasitnikov/887e240be9b08b35d0b67516d4e6ce08

```
npm i
./node_modules/.bin/tsc
```

#### Actual behavior
Compilation errors:

```
node_modules/popper.js/index.d.ts(38,5): error TS2411: Property 'shift' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(39,5): error TS2411: Property 'offset' of type '(BaseModifier & { offset?: string | number | undefined; }) | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(42,5): error TS2411: Property 'preventOverflow' of type '(BaseModifier & { priority?: Position[] | undefined; padding?: number | undefined; boundariesElem...' is not assignable to string index type 'Base
Modifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(47,5): error TS2411: Property 'keepTogether' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(48,5): error TS2411: Property 'arrow' of type '(BaseModifier & { element?: string | Element | undefined; }) | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(51,5): error TS2411: Property 'flip' of type '(BaseModifier & { behavior?: Position[] | "flip" | "clockwise" | "counterclockwise" | undefined; ...' is not assignable to string index type 'BaseModifier &
Record<string, any>'.
node_modules/popper.js/index.d.ts(56,5): error TS2411: Property 'inner' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(57,5): error TS2411: Property 'hide' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(58,5): error TS2411: Property 'applyStyle' of type '(BaseModifier & { onLoad?: Function | undefined; gpuAcceleration?: boolean | undefined; }) | unde...' is not assignable to string index type 'BaseModif
ier & Record<string, any>'.
```

It seems it is the same bug here: https://github.com/FezVrasta/popper.js/issues/414

### PR DESCRIPTION
**Pull request by adidahiya**
⚠️ Targeting branch `ad/workspaces`

Fixes #116.
Fixes #436.
Fixes #1527.
Fixes #780.

### Changes proposed:

Replace Gulp build tooling with Lerna & NPM scripts. Each package now has its own list of `"scripts"` in `package.json`. There are a few new private packages which help us manage build configuration. The three types of packages are:

- __libraries__: core, datetime, labs, table
  - these are our UI libraries that we publish on NPM
- __applications__: landing-app, docs-app
  - these require bundling with webpack
  - I renamed these from site-landing and site-docs because I feel like "application" much better represents what they are; they're not static web pages
- __build tooling__: webpack-build-scripts, karma-build-scripts, tslint-config
  - these new private packages help us:
    - keep clear API boundaries for build configuration
    - isolate groups of dev dependencies
  - in the future, we might publish these packages for use in other blueprint repos

A decent amount of cruft was removed in this process:

- Removed all usage of the deprecated `typings` registry in favor of `@types` packages from NPM.
- All projects share tsc configuration using TypeScript's `"extends"` inheritance feature (it was unsupported in `gulp-typescript`).

There is a new publishing workflow. I brought over some of our internal monorepo build scripts to handle publishing using Lerna publish commits (generated by `lerna publish`).

And a few random enhancements:

 - Faster CI builds with concurrent containers -- we run `dist`, `test`, and `lint` in parallel.

### Further improvements to be addressed in future PRs

- Fix skipped table unit tests #1794 
- Enable `no-implicit-dependencies` lint rule
- Bring [documentalist](https://github.com/palantir/documentalist/) into this repo (it's languishing out there on its own, unloved 😢)
- Switch test runner from phantomjs to headless Chrome
- UMD bundle externals #1805 
- import from `"sinon"` in a consistent way
- use node-sass-chokidar (#1134)
- watch variant of `generate-docs-data`

### Remaining tasks

- [x] landing-app
  - [x] compiling
  - [x] bundle assets correctly
  - [x] webpack dev setup
- [x] docs-app
  - [x] examples compiling
  - [x] webpack dev setup
  - [x] run documentalist
- [x] misc. scripts, tests
  - [x] generate icons
  - [x] isomorphic tests
  - [x] generate sass / less variables files
- [x] table
  - [x] build src and test
  - [x] tests pass (had to skip some tests... https://github.com/palantir/blueprint/issues/1794)
  - [x] webpack dev setup
- [x] delete Gulp build code
- [x] dev documentation
- [x] core
  - [x] build src and test
  - [x] tests pass
- [x] datetime
  - [x] build src and test
  - [x] tests pass
- [x] labs
  - [x] build src and test
  - [x] tests pass

### CODE REVIEW

**Comment by adidahiya** [comment]
it's beautiful 😂 
image

**Comment by JacekJagiello** [comment]
@adidahiya That's great, thanks for removing Gulp :D

File: circle.yml [hunk 1]
```diff
@@ -14,7 +14,7 @@ general:
     - packages/datetime/dist
     - packages/docs/dist
     - packages/labs/dist
-    - packages/site-docs/dist
+    - packages/docs-app/dist
     - packages/site-landing/dist
```
Comment (giladgray) [inline circle.yml]: landing-app?

File: packages/core/karma.conf.js [hunk 2]
```diff
@@ -3,6 +3,7 @@
  */
 
 const { createKarmaConfig } = require("@blueprintjs/karma-build-scripts");
+const fs = require("fs");
```
Comment (giladgray) [inline packages/core/karma.conf.js]: unused import?

File: packages/node-build-scripts/assert-package-layout [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+const fs = require("fs");
+const path = require("path");
+
+// asserts that all main fields in package.json reference existing files
+const PACKAGE_MAIN_FIELDS = ["main", "style", "typings", "unpkg"];
+const manifest = require(path.resolve(process.cwd(), "./package.json"));
+
+for (let field of PACKAGE_MAIN_FIELDS.filter(field => manifest[field] !== undefined)) {
+    if (!fs.existsSync(path.resolve(process.cwd(), manifest[field]))) {
+        console.error("[node-build-scripts] Failed to validate package layout.");
```
Comment (giladgray) [inline packages/node-build-scripts/assert-package-layout]: can we provide a better error with the missing field?

File: packages/webpack-build-scripts/index.js [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+ * Copyright 2017 Palantir Technologies, Inc. All rights reserved.
+ * Licensed under the terms of the LICENSE file distributed with this project.
+ */
+
+const baseConfig = require("./webpack.config.base");
+
+module.exports = {
+    baseConfig,
+
+    COMMON_EXTERNALS: {
```
Comment (giladgray) [inline packages/webpack-build-scripts/index.js]: easy enough to fix #1805 while we're at it?

Comment (adidahiya) [reply packages/webpack-build-scripts/index.js]: not really, i'd like to do that in a separate PR

File: README.md [hunk 5]
```diff
@@ -17,42 +17,85 @@ If you rely heavily on mobile interactions and are looking for a mobile-first UI
...
+- Run `yarn compile-libs` to get the latest built versions of the library packages in this repo.
+  - This command is quicker than `yarn verify` since it doesn't build the application packages (`workspace-chrome`, `workspace-docs`, etc.) or run tests
 
-### Updating build dependencies
+### Developing libraries
 
-1. `yarn add <package-name>` or `yarn upgrade <package-name>`.
+Each library has its own dev script which you can run to watch changes to that package and run the docs application with webpack-dev-server: `yarn dev:core`, `yarn dev:datetime`, etc.
+
+- One exception is table &mdash; since it has its own playground application for development, it `dev:table` script doesn't run the docs site.
```
[the remark this answers is not in the document]
Comment (cmslewis) [reply README.md]: Also, typo? 

...playground application for development, **it** `dev:table` script doesn't run...

[the remark this answers is not in the document]
Comment (cmslewis) [reply README.md]: Also, maybe back ticks around `table` to clarify that it's a package name?

File: README.md [hunk 6]
```diff
@@ -17,42 +17,85 @@ If you rely heavily on mobile interactions and are looking for a mobile-first UI
...
+- You may also choose to watch changes across all packages with `dev:all`.
```
Comment (cmslewis) [inline README.md]: Clearer:

> You may also choose to watch changes across all packages by running `yarn dev:all` from the root directory.

?

File: README.md [hunk 7]
```diff
@@ -17,42 +17,85 @@ If you rely heavily on mobile interactions and are looking for a mobile-first UI
...
+
+1. Edit the `package.json` where you wish to change dependencies.
+1. Run `yarn` at the root to update lockfiles.
 1. Commit the result.
 
-### Updating package dependencies
+### Updating documentation
+
+Much of Blueprint's documentation lives inside source code as JSDoc comments in `.tsx?` files and KSS markup in `.scss` files. This documentation is extracted
+and converted into static JSON data using [documentalist](https://github.com/palantir/documentalist/).
```
Comment (cmslewis) [inline README.md]: nit: newlines here are kinda weird. can we kick it to one line for simplicity in the editor?

File: README.md [hunk 8]
```diff
@@ -17,42 +17,85 @@ If you rely heavily on mobile interactions and are looking for a mobile-first UI
...
+
+If you are updating documentation sources (_not_ the docs UI code which lives in `packages/docs-app`), you'll need to run `yarn generate-docs-data` from the `docs-app`
+package to see it reflected in the application. Note that `yarn bundle` in this package also runs this script.
```
Comment (cmslewis) [inline README.md]: Same

Comment (cmslewis) [reply README.md]: Also, is there a `watch` variant of this command?

File: package.json [hunk 9]
```diff
@@ -1,25 +1,34 @@
...
+    "clean": "lerna run clean",
+    "clean-gh-pages": "rm -rf docs && git checkout docs/CNAME",
+    "copy-docs-app": "cp -rf packages/docs-app/dist docs/docs",
+    "copy-landing-app": "cp -rf packages/landing-app/dist/* docs/.",
+    "dev:all": "lerna run dev",
+    "dev:core": "lerna run dev --scope '@blueprintjs/{core,docs-app}'",
+    "dev:docs": "lerna run dev --scope '@blueprintjs/docs-app'",
+    "dev:datetime": "lerna run dev --scope '@blueprintjs/{core,datetime,docs-app}'",
+    "dev:labs": "lerna run dev --scope '@blueprintjs/{core,labs,docs-app}'",
+    "dev:table": "lerna run dev --scope '@blueprintjs/table'",
```
Comment (cmslewis) [inline package.json]: Should this be `'@blueprintjs/{core,table}'`, since `table` uses utilities from `core`?

File: packages/core/test/tsconfig.json [hunk 10]
```diff
@@ -1,9 +1,7 @@
...
-        "**/*"
-    ],
-    "exclude": []
-}
+    "extends": "../../../config/tsconfig.base",
+    "compilerOptions": {
+        "declaration": false,
+        "noEmit": true
+    }
+}
```
Comment (cmslewis) [inline packages/core/test/tsconfig.json]: Need a newline here

File: packages/datetime/test/dateRangeInputTests.tsx [hunk 11]
```diff
@@ -7,6 +7,7 @@
 import { expect } from "chai";
 import { mount, ReactWrapper } from "enzyme";
 import * as React from "react";
+import * as sinon from "sinon";
```
Comment (cmslewis) [inline packages/datetime/test/dateRangeInputTests.tsx]: The sinon imports are inconsistent between packages. `core` imports sinon dependencies like this:

```tsx
import { Sinon, SinonSpy } from "sinon";
```

Whereas `datetime` imports everything as one module. Can we pick just one scheme?

File: packages/tslint-config/index.js [hunk 12]
```diff
@@ -0,0 +1,79 @@
...
+        "no-submodule-imports": {
+            options: [
+                "documentalist",
+                "lodash",
+                "react-dom"
+            ]
+        },
+        "no-unnecessary-callback-wrapper": true,
+        "no-unnecessary-initializer": true,
+        // TODO: enable no-unused-expression. Currently, a lot of chai assertions are not writtten as proper statements.
```
Comment (cmslewis) [inline packages/tslint-config/index.js]: nit: typo: `written`

File: packages/tslint-config/package.json [hunk 13]
```diff
@@ -0,0 +1,22 @@
...
+    "tslint-plugin-prettier": "^1.3.0",
+    "tslint-react": "^3.2.0"
+  },
+  "repository": {
+    "type": "git",
+    "url": "git@github.com:palantir/blueprint.git"
+  },
+  "author": "Palantir Technologies",
+  "license": "Apache-2.0"
+}
```
Comment (cmslewis) [inline packages/tslint-config/package.json]: newline

File: packages/webpack-build-scripts/utils.js [hunk 14]
```diff
@@ -0,0 +1,27 @@
...
+    let name;
+    try {
+        name = require(path.join(process.cwd(), "package.json")).name;
+        // strip NPM scope, if possible
+        const nameSplit = name.split("/");
+        if (nameSplit.length > 1) {
+            name = nameSplit[1];
+        }
+    } catch (e) {
+        console.error("[webpack-build-scripts] Couldn't read packge name from package.json", e);
```
Comment (cmslewis) [inline packages/webpack-build-scripts/utils.js]: nit: typo: `package`

File: packages/webpack-build-scripts/webpack.config.base.js [hunk 15]
```diff
@@ -0,0 +1,121 @@
...
+            },
+        }),
+
+        // Some loaders accept configuration through webpack internals
+        new webpack.LoaderOptionsPlugin({
+            debug: false,
+            minimize: true,
+        }),
+
+        // Only extract CSS to a file for production because it is slow
```
[the remark this answers is not in the document]
Comment (cmslewis) [reply packages/webpack-build-scripts/webpack.config.base.js]: ➕  1️⃣

File: packages/datetime/test/dateRangeInputTests.tsx (hunk 11 above)
Comment (adidahiya) [reply packages/datetime/test/dateRangeInputTests.tsx]: I started off by adding named sinon imports and later realized that I could have a much smaller diff if I switched to namespace imports in the other packages. I'm going to hold off on standardizing in this PR and leave it as a follow-up

**Comment by adidahiya** [comment]
almost good to go... missing some assets in the statically built artifacts:

- [ ] icon font in docs site
- [ ] svg images (non-inline ones) in landing app

File: Gulpfile.js [hunk 16]
```diff
@@ -98,10 +98,6 @@ const projects = [
             entry: "src/index.tsx",
```
Comment (adidahiya) [inline Gulpfile.js]: should delete this file

File: packages/core/src/components/card/card.tsx [hunk 17]
```diff
@@ -58,7 +58,7 @@ const ELEVATION_CLASSES = [
 export class Card extends React.Component<ICardProps, {}> {
     public static displayName = "Blueprint.Card";
     public static defaultProps: ICardProps = {
-        elevation: Elevation.ZERO,
```
Comment (jrafidi) [inline packages/core/src/components/card/card.tsx]: seems wrong?

File: packages/labs/test/tsconfig.json [hunk 18]
```diff
@@ -1,10 +1,7 @@
...
-        "**/*"
-    ],
-    "exclude": []
-}
+    "extends": "../../../config/tsconfig.base",
+    "compilerOptions": {
+        "declaration": false,
+        "noEmit": true
+    }
+}
```
Comment (jrafidi) [inline packages/labs/test/tsconfig.json]: newline

File: packages/node-build-scripts/package.json [hunk 19]
```diff
@@ -0,0 +1,23 @@
...
+  "dependencies": {
+    "strip-css-comments": "^3.0.0"
+  },
+  "repository": {
+    "type": "git",
+    "url": "git@github.com:palantir/blueprint.git"
+  },
+  "author": "Palantir Technologies",
+  "license": "Apache-2.0"
+}
```
Comment (jrafidi) [inline packages/node-build-scripts/package.json]: newline

File: packages/webpack-build-scripts/webpack.config.base.js [hunk 20]
```diff
@@ -0,0 +1,141 @@
...
+// Module loaders for .scss files, used in reverse order (compile Sass, apply PostCSS, interpret CSS as modules)
+const scssLoaders = [
+    {
+        loader: require.resolve("css-loader"),
+        options: { minimize: IS_PRODUCTION },
+    },
+    {
+        loader: require.resolve("postcss-loader"),
+        options: {
+            config: { path: path.resolve(__dirname, "postcss.config.js") },
```
Comment (jrafidi) [inline packages/webpack-build-scripts/webpack.config.base.js]: where does this `__dirname` resolve? usage on line 100 implies it resolves in the directory in which webpack is being run, so is postcss not happening?

**Comment by adidahiya** [comment]
:shipit:
